### ISSUE TITLE
Enhancement request: Stay open after failure to connect

### ISSUE THREAD

**Issue by fribse** [taburineagle/NeewerLite-Python#19]
Currently if a light fails to connect, the application exits, I would like it to stay open :-)

**Comment by taburineagle** [comment]
Ha, that shouldn't be happening, it should re-attempt to link to the light for as many times specified in `maxNumOfAttempts`, which is also settable in the global preferences tab.  When you say "exits", do you mean it just closes, or does it error out?

**Comment by taburineagle** [comment]
Or is this with CLI mode?  Because it does quit out on issues in CLI mode.  Ha, I need a little more info for this one 😊

**Comment by fribse** [comment]
I'm currently running the GUI only. Not even with the webserver, haven't had the time to put it in the streamdeck even :-)
If it fails to connect, then it retries 6 times, and then exits.
I think it should just continue with the next light. Then one could try and fix the connection problem and try reconnecting later?
I'm running it from an icon, so it launches the commandprompt, that unfortunately also means that when it exits, it automatically closes the commandprompt window, so I can't say if there are any errors until I can provoce the problem again.

**Comment by taburineagle** [comment]
I saw a later posting that this issue went away for you - the program shouldn't be quitting out after erroring out, it should just say "The light failed to link" or something along those lines, and then you'd just need to hit "Connect" again to try a 2nd time - this _might_ have been because the `NeewerLite-Python.py` file and `ui_NeewerLightUI.py` files aren't from the same version.

**Comment by taburineagle** [comment]
I'm not sure what was causing this one... I _think_ it might have been due to a `NeewerLite-Python.py` file and `ui_NeewerLightUI.py` mismatch, but I'm not 100% sure on that... but I'm going to close this for now. If you continue having issues with the program quitting out like this after connection failures, feel free to re-open it!
