### ISSUE TITLE
Can't start UI

### ISSUE THREAD

**Issue by Desaydrone** [taburineagle/NeewerLite-Python#59]
Hello,

When i try to launch the UI i got this error

```log
---------------------------------------------------------
             NeewerLite-Python ver. 0.12b
                 by Zach Glenwright
  > https://github.com/taburineagle/NeewerLite-Python <
---------------------------------------------------------
Traceback (most recent call last):
  File "/home/myuser/Documents/script/NeewerLite-Python/NeewerLite-Python.py", line 3414, in <module>
    mainWindow = MainWindow()
                 ^^^^^^^^^^^^
  File "/home/myuser/Documents/script/NeewerLite-Python/NeewerLite-Python.py", line 189, in __init__
    self.setupUi(self) # set up the main UI
    ^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Documents/script/NeewerLite-Python/ui_NeewerLightUI.py", line 133, in setupUi
    self.CCT_Temp_Gradient_BG.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
````

Did i miss something ? have someone an idea ?

Thanks a lot

**Comment by fribse** [comment]
Did you get the PySide2 installed? And it is available in the python? What platform is it you are using it on?
I'm not using the GUI version, I've set it up with http and I'm using my streamdeck for it, so for me it's quite some time ago I had it set up on my windows box.

**Comment by Desaydrone** [comment]
I'm on linux Fedora 37, yes i install PySide2 for my user and in root to.

I'm going to use it with the cli line ;) to use it with touch portal, but for purpose test i was trying by gui. But nice tips to use it with http !! i look at this thanks :)

I give a try for http thanks :)

**Comment by taburineagle** [comment]
@Desaydrone - which version of Python and PySide2 are you using?  I saw Fedora 37, so I'm assuming it's a flavor of Python 3, which _shouldn't_ toss that error, but I'm not 100 sure...

**Comment by Desaydrone** [comment]
The Pyside2 version is : PySide2-5.13.2
The python version is : 3.11.1

**Comment by taburineagle** [comment]
That's interesting - kind of a bizarre error, as that line `self.CCT_Temp_Gradient_BG.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)` is written how PySide2 expects it to be written, so I'm not 100% sure where that's coming from...  I do have a Fedora 17 VM to test things out with, but not that specific Python or PySide2 variant, so that would take some time to test out.  I have had luck in getting Fedora to work with NeewerLite-Python though, so maybe it's some weird quirk with that combination.

**Comment by taburineagle** [comment]
Hey @Desaydrone - a bit of a long time since this issue was closed, but I'm fairly certain I've got the issue fixed.  Older versions of PySide2 < 5.15 apparently have issues when you splice multiple Alignment values together.  I changed the way I do that to just add them as integers and then convert them to the correct type after the addition.  I have one other person who also has that issue that needs to test the new method out, and when I get the all clear, I'll push the new version as a release.
