### ISSUE TITLE
Enhancement request: Multiple lights with different values via http

### ISSUE THREAD

**Issue by yankijp** [taburineagle/NeewerLite-Python#61]
Hello!,

Very much enjoying this. I am using it for an indie production as I didn't have enough funds set aside for DMX spots and I am using the RGB CB60.

Works great so far but since I am trying to update the max amount of lights with different values (7 lights is the most I can pair due to the Bluetooth spec max) it takes a while. Since it seems via a PC I can run around 2 http requests in a second without it saying that it is processing a command. It would take me around 3.5 seconds to change all the values on 7 lights using 7 http requests. When using the parameters for multiple lights I can only change those lights to the same values but not different values for each light.

A stretch goal for me would be able to send the commands for all 7 lights at 30 fps so I can animate the lights in real-time but it would be awesome if I can send 7 commands for lights even two times a second. 

A little background is that I have a graphics program on one machine sending http commands to the python running on another machine. 

Thanks!

**Comment by taburineagle** [comment]
Hi @yankijp - glad to hear that NeewerLite-Python is working well for you!  I've only tested 3 at once, so that's great to hear that 7 works fine, although I can imagine there'd be a bit of lag sending commands to all 7 of them at the same time.  With the GUI, I do have settable snap and global presets, which save the state of either the global (controls all lights at the same time) and snap (it saves a snapshot of where each light is at that specific moment and can re-set those parameters for all of the selected lights at the same time) presets that can control multiple lights with different values all at the same time.  If you have a snap/global preset set up through the GUI, you can launch it on the HTTP server, but I haven't programmed a routine to _save_ those presets via the HTTP server yet, that might help out a little with what you're trying to achieve.

**Comment by taburineagle** [comment]
Hi @yankijp - I'm going to close this as I haven't heard back in a while - if you have any similar issues, feel free to reopen it!
