### ISSUE TITLE
Can't run the 2 .pt programs

### ISSUE THREAD

**Issue by CongaTom** [taburineagle/NeewerLite-Python#64]
Hi

This has been a big learning curve for me. I've never used the Terminal before for anything. And I've never used GitHub.

My goal is to control my Neewer lights from Streamdeck.

But I'm having problems running the 2 .py programs.

I'm using MacOS Monterey 12.6.3.
I upgraded my terminal to zsh

I tried uploading Pyside2 and Python3 but got confused about PATH, so I uninstalled them. I think.
I then used Homebrew and uploaded Python3 and Pyside2. QT5 failed during that, so I uploaded it separately.

I downloaded the .zip file and unzipped it and moved it to Applications folder.

I tried to run NeewerLite-Python.py on the terminal but it said I didn't have PySide2 Python library installed. So I typed in "pip3 install PySide2" in the terminal.

Now when I first run the UI .py program by right clicking and choosing Python3 Launcher app it comes up with this screenshot of the Terminal. Then when I run the other .py program by right clicking and choosing Python3 Launcher app it says "it's already running, but would you like to run it anyway?". I click Yes, and it comes up with this other screenshot.

I've done as much research as I possibly could. I don't know what to do next.

<img width="638" alt="running the UI" src="https://user-images.githubusercontent.com/125425451/218923059-c89e2292-a126-4bbe-a68c-f2934b6f5e51.png">
<img width="638" alt="Running NeewerLite-Python" src="https://user-images.githubusercontent.com/125425451/218923083-ecf06d1b-c9ed-43b5-a49d-8b38ee22d73f.png">

**Comment by taburineagle** [comment]
Hi @CongaTom - I'm sorry you're having issues running the program!  I've seen other error reports showing the same error (the "object cannot be interpreted" error) from other people, but I haven't seen it in my own testing.  I _think_ I understand where it's coming from though - give me a little time to check into it and I'll post an update that will (hopefully) fix that.  Everything else you've done looks good, you have PySide2 and the program isn't reporting that it's missing, although I don't know if you needed to update to zsh, I use the default Mac OS X terminal when I run it on my system.

**Comment by CongaTom** [comment]
Thanks for that.
I only updated to zsh because a message in terminal recommended that I do it.
:-)

**Comment by taburineagle** [comment]
Ah, ha, I stand corrected - I just looked at my Terminal and saw it also was using zsh, so that answers that 😄  OK, I tweaked the setAlignment flags to hopefully correct the "can not be interpreted" issue, but I haven't added those changes into the main branch yet.  Try this version out to see if you still get that error -

[https://codeload.github.com/taburineagle/NeewerLite-Python/zip/refs/heads/setAlignment-WIP](https://codeload.github.com/taburineagle/NeewerLite-Python/zip/refs/heads/setAlignment-WIP)

**Comment by CongaTom** [comment]
Hi @taburineagle 

I'm not sure whether I can just delete the previous folder with all the filers in it,or whether i need to uninstall it somehow. So if you could please advise on that that would be great.
So I downloaded the next version of the file that you posted above, put it into Applications folder and first I ran NeewerLite-Python.py, and 4 windows came up:

<img width="638" alt="230220 Running NeewerLite-Python window 1" src="https://user-images.githubusercontent.com/125425451/220034765-c0c9b7d4-d63e-4700-bff9-f2aab2c5c482.png">
<img width="493" alt="230220 Running NeewerLite-Python window 2" src="https://user-images.githubusercontent.com/125425451/220034781-bffdf1e5-0c4a-49a0-a54c-5f9ced876e60.png">
<img width="488" alt="230220 Running NeewerLite-Python window 3" src="https://user-images.githubusercontent.com/125425451/220034790-1e10f4de-b8de-4569-a7c7-8fe4e5540462.png">
<img width="638" alt="230220 Running NeewerLite-Python window 4" src="https://user-images.githubusercontent.com/125425451/220034803-fbb66b68-7d56-4532-ae99-91f2f3340397.png">


I pressed Launched New Instance and nothing happened....Or maybe the windows above became as they were above at that point. Anyway, nothing else happened.

So then I ran ui_NeewerLightUI.py and this happened:

<img width="638" alt="230220 Running ui_NeewerLightUI window 1" src="https://user-images.githubusercontent.com/125425451/220035375-9aef76d0-e837-41e7-8756-33193db43d88.png">
<img width="638" alt="230220 Running ui_NeewerLightUI window 2" src="https://user-images.githubusercontent.com/125425451/220035406-385c1705-cd19-4258-8b48-41eb691d872d.png">

So, no luck with the modification I think..

**Comment by CongaTom** [comment]
Actually, when I pressed Launch New Instance, this one came up:

<img width="638" alt="230220 Running NeewerLite-Python window 5" src="https://user-images.githubusercontent.com/125425451/220037655-eec424f5-9f01-4a0a-ad54-7aa324d3ffed.png">

**Comment by taburineagle** [comment]
Ah, I could see how that would have been confusing, sorry about that - yeah, you can delete the old version of NeewerLite-Python you downloaded and just use the version in the .zip file I specified, *although* I think I may have figured out the actual problem.  If what I think _is_ the actual problem is, I don't know why the compiler didn't tell me there was an issue before (the program has run fine on all of the platforms I've tested it with - so either they're ignoring the issue at hand or the version of PySide2 I'm using is strangely wired.)  I think I need to use PySide2.**QtCore**.Qt and not PySide2.**QtGUI**.Qt - let me do some testing on that (I don't have my laptop with me at the moment, so I can't test that right now), and I'll get back to you.

**Comment by taburineagle** [comment]
OK @CongaTom - I've made the import changes on my end and pushed the commit to the main branch.  Try this version out and see if you have the same "cannot be interpreted" error.  You can delete the NeewerLite-Python-setAlignment-WIP folder and use the scripts from this zip file:

[https://github.com/taburineagle/NeewerLite-Python/archive/refs/heads/main.zip](https://github.com/taburineagle/NeewerLite-Python/archive/refs/heads/main.zip)

**Comment by CongaTom** [comment]
Hi @taburineagle 

Sad to say I think the same problem exists....
But do you find it strange that the Python app is showing two icons?

<img width="488" alt="Untitled 1" src="https://user-images.githubusercontent.com/125425451/221078069-6135814a-27da-45a1-bff8-93eb2e797717.png">
<img width="638" alt="Untitled 2" src="https://user-images.githubusercontent.com/125425451/221078099-cc768dad-2ed3-4930-b656-5c25f183bf4b.png">
<img width="638" alt="Untitled 3" src="https://user-images.githubusercontent.com/125425451/221078112-150cb9cd-94b8-4d1a-a0b1-4db3fb9f495a.png">
<img width="493" alt="Untitled 4" src="https://user-images.githubusercontent.com/125425451/221078124-e9c41e77-efb3-4097-909e-5913f4c2a20f.png">

After "Launch New Instance":

<img width="638" alt="After Launch New Instance" src="https://user-images.githubusercontent.com/125425451/221078295-9021a248-7211-45fa-be4f-23f94e509105.png">

2 icons running for the same app??

<img width="39" alt="Untitled 5" src="https://user-images.githubusercontent.com/125425451/221078444-a29cc56c-6c4f-4e32-8542-1825f37f24e6.png">

**Comment by taburineagle** [comment]
_Huh_ - I'm not sure why that error keeps popping up, nothing's being converted to an integer in that parameter at all 🤔  The two icons _kind_ of make sense - I'm assuming the first one is running the initial copy, and the 2nd one is running the version you're telling to "ignore" the first copy, but that error still confuses me.  I also wish I had a test setup that would replicate the results so I could find it more thoroughly, but I've never seen that error myself in any of my testing, on Windows, Mac or Linux... yet I've had multiple reports of it happening on some installs.  Let me do a bit more investigating...

**Comment by taburineagle** [comment]
OK, if you type

`pip show PySide2`

In the terminal, what version does it show you're running?  I'm wondering if there _might_ be a discrepancy in versions - _possibly_...  I'm using 5.15.2.1, and in doing some Google searches, I have seen a few entries talking about errors with PySide2 and Python 3.8, but I'm not sure how far that goes back.

[https://codereview.qt-project.org/c/pyside/pyside-setup/+/288381/5](https://codereview.qt-project.org/c/pyside/pyside-setup/+/288381/5)

**Comment by CongaTom** [comment]
I'm not sure what you mean by the "initial copy", because what i do is I quit both Python and Terminal, so nothing is running, then I run your latest version (atm it's NeewerLite-Python.py). And it just creates 2 icons, and tells me that "another instance .. is already running". But I only opened it once. When I press on one Python icon, it shows the Preferences window. When I press on the other Python icon it shows the "Another Instance..." message window.

Here's what happened when I typed in pip show PySide2:

<img width="638" alt="230301 show Python" src="https://user-images.githubusercontent.com/125425451/222043522-ae3d77a2-dfde-4fea-9cea-341dc30eba06.png">

**Comment by CongaTom** [comment]
maybe i've installed it wrong, or I've duplicated something? I know that it didn't behave like I thought it would and I tried once or twice to install things...

**Comment by taburineagle** [comment]
Sorry for the late reply @CongaTom, last week turned out to be a lot busier than anticipated!  *Ah*, actually I think you do have an older version of PySide2 - the latest version is 5.15.2.1, the tech note I mentioned (that has the integer issue) says it's from 5.14, and you have 5.13 installed (according to the `pip show PySide2` command readout in your screenshot, it says *5.13.2*), but I'm still not sure why the older versions of PySide considered those variables as integers in the first place as they definitely aren't.  OK, next step, try this and see if `pip` will allow you to upgrade your version of PySide2:

`pip install --upgrade PySide2`

If not, let me see if I can create a virtual machine/venv to test with using the old version to see if I can work out the strange integer/hex conversions that are going on there.  As far as the "initial copy" I'm talking about, when you run NeewerLite-Python first, it doesn't quite get to the GUI (due to the integer issue with PySide2), but it does get far enough in the code to generate the "lock" file that shows future launches of the program that it was started at some point in the past.  So when you launch it again, even though the integer issue still doesn't let it launch the whole way, the next launch finds that "lock" file and alerts you that you may have another copy running, hence the "There is another instance of..." dialog.

**Comment by CongaTom** [comment]
Looks like I can't upgrade any further? 
I'm using Mac OS Monterey version 12.6.3 on a MacBook Pro (15-inch, 2016)
<img width="638" alt="230307 screenshot" src="https://user-images.githubusercontent.com/125425451/223337024-fbce91de-1fad-442e-8c0d-312679afc808.png">

**Comment by taburineagle** [comment]
Ah, that's interesting @CongaTom - it might be because you installed Python with Homebrew, but I'm not sure... **But!** - I think I've figured the problem out.  I was able to get a venv session set up with the older version of PySide2 and I also got the same error, so to fix it, I changed the method for combining Alignment flags for all versions of PySide2.  The GUI _should_ launch correctly now, I tested it with PySide2 5.13.2, and everything loads correctly for me now.

Here is the new version - [https://codeload.github.com/taburineagle/NeewerLite-Python/zip/refs/heads/main](https://codeload.github.com/taburineagle/NeewerLite-Python/zip/refs/heads/main)

**Comment by CongaTom** [comment]
Ok. It's either getting MUCH closer, or, this could be it!
This will take a bit of reporting...
I downloaded the zip file, put it into my Applications folder, and unzipped.
I made sure both Terminal and Python were Quit.
I ran NeewerLite-Python.py
It came up with these 4 windows, and another window asking me if I wanted it to use Bluetooth (or some words similar to that) I pressed Yes and it went away. The 2 iterations of Python icon still come up in the dock.
<img width="493" alt="Untitled" src="https://user-images.githubusercontent.com/125425451/223619082-fc2336bf-4423-489d-b4d5-99a2b21c213b.png">
<img width="638" alt="Untitled 2" src="https://user-images.githubusercontent.com/125425451/223619097-d4988bbc-d322-4998-bde8-463c8195ac16.png">
<img width="638" alt="Untitled 3" src="https://user-images.githubusercontent.com/125425451/223619101-d4216b48-5a37-409b-880a-bd306a825eda.png">
<img width="658" alt="Untitled 4" src="https://user-images.githubusercontent.com/125425451/223619105-5d31b375-73f1-4201-98b1-16bb698e33ef.png">

I think that's a great step forward!

I quit them all totally, and repeated the same procedure.
And got these 4 windows:

<img width="493" alt="Untitled" src="https://user-images.githubusercontent.com/125425451/223619704-5c90b418-f34f-42a7-8ca1-86512cc96e3f.png">
<img width="638" alt="Untitled 2" src="https://user-images.githubusercontent.com/125425451/223619730-68bbe1ea-ba20-4634-8c54-60609c0a8caa.png">
<img width="638" alt="Untitled 3" src="https://user-images.githubusercontent.com/125425451/223619739-e44d1f74-9cf2-4acc-97ec-0f8a9820d4f2.png">
<img width="658" alt="Untitled 4" src="https://user-images.githubusercontent.com/125425451/223619747-b31379f8-a8ce-4361-9774-c29573ba3097.png">

I quit them all totally and ran ui_NeewerLightUI.py, and got these windows:

<img width="493" alt="Untitled" src="https://user-images.githubusercontent.com/125425451/223620211-c065d014-f115-4a88-be02-d8993f5a8b1c.png">
<img width="638" alt="Untitled 2" src="https://user-images.githubusercontent.com/125425451/223620230-ac9c49b4-0307-4fe5-9c37-bb049598bbc2.png">
<img width="638" alt="Untitled 3" src="https://user-images.githubusercontent.com/125425451/223620237-9244b9bb-685f-42c1-9d4f-0d8ac978a45d.png">

So, does everything work now? If so, what is ui_NeewerLightUI.py used for? What do I do with it?

**Comment by taburineagle** [comment]
That's it!  The errors you got in the first set of screenshots just tell you Bluetooth is turned off - NeewerLite-Python needs Bluetooth turned on, because that's how it communicates with the lights.  `ui_NeewerLightUI.py` on its own is just the GUI (the main window) - launching it on its own won't do anything, it's just a file that `NeewerLite-Python.py` uses to draw the window you interact with when you use GUI mode.

**Comment by taburineagle** [comment]
Ah, excellent!  I'm going to close this one then, because the GUI does work, and I'll head on over to the other one.
