### ISSUE TITLE
Testing the webserver usage - ON/OFF?

### ISSUE THREAD

**Issue by fribse** [taburineagle/NeewerLite-Python#7]
Hi Zack, I just updated the files anyway, can't wait 😆 

I have some intermittent connection problems on the first connect, this makes it difficult to set something up automatically at the moment.
Also, how do I turn on/off through the web interface?

**Comment by taburineagle** [comment]
Ha, well, you _couldn't_ - at least before... 😅  I just added that feature in ^^ - in the newest commit, if you're in the CLI, add `--on` or `--off` to the command line - for the HTTP server, just pipe |on or |off into the command, like this:

`http://127.0.0.1:8080/NeewerLite-Python/light=1;2|off`
`http://127.0.0.1:8080/NeewerLite-Python/light=1;2|on`

I've had a few issues with linking on the first attempt too, I still believe it's a Bluetooth dongle issue on my end, because that seems to happen more frequently when the lights are farther away from the PC.

**Comment by fribse** [comment]
Well, most bt dongles range 5-10m, mine is placed on a powered usb3 hub on my desk, so the distance is below 2m to each of them, and it still acts up :-)
I've gotten my second SNL-660, things are looking much brighter now 😆 
Today they both connected without any second attempts.

**Comment by taburineagle** [comment]
Ha, nice 😁  Yeah, I've had varied success myself too - sometimes they're only a few feet away from the PC, and they don't connect the first time - I haven't had as many issues with laptops connecting, so I wonder if something else in the room might be interfering?  Either way, they usually connect on the 2nd try if the first one is no good, so maybe the link procedure should try two times before erroring out.

**Comment by fribse** [comment]
I had issues today with the connection, only one of the lights connected on the first attempt, and then it couldn't figure out what to do when I asked it to connect to both of them again, when one was already connected, selecting the disconnected again, made it connect, and the lights didn't misbehave after that.

**Comment by taburineagle** [comment]
Got you - which interface is that you had issues with, GUI, CLI or HTTP?  I'm assuming HTTP because that's the thread this post is in, but I'm not sure :)  It sounds like most of the issues you've been having is with the linking stage, I definitely should add some "try again" conditionals if they don't link properly the first time around.

**Comment by taburineagle** [comment]
@fribse - I added a multiple retry condition to the latest commit - this way, if the light doesn't link on the first attempt, it will try until the number of maximum attempts (at the moment specified by the `maxNumOfAttempts` variable at the top of the script) to link up to it.

**Comment by taburineagle** [comment]
@fribse - I'm going to close this issue now, because it's been 7 days and as far as I've been able to test, should be fixed now... if you still have issues with it, feel free to reopen it!
