### ISSUE TITLE
All of the sudden "CAN NOT FIND BLEAK LIBRARY"

### ISSUE THREAD

**Issue by markvrepo** [taburineagle/NeewerLite-Python#73]
I'm not sure what changed (about the only thing recent and obvious is removal of NVIDIA Broadcast and a .NET 7.0 SDK install.).  I'm getting this error - CAN NOT FIND BLEAK LIBRARY.  I've tried reinstalling/uninstalling/installing bleak to no effect.  Anyone else seeing this ?  Occurs with the current version of NeewerLite and a prior version (not sure which one but it had been working for a year).

Any thoughts ?  Looking into how to test Bleak more generally.  Thanks

**Comment by taburineagle** [comment]
To me (just speculating), that almost sounds like multiple versions of Python running on your system - I'm not 100% sure of what's in the .NET 7.0 SDK (I have Visual Studio 2022 myself, and it has a version of the .NET SDK as part of it also, but I don't know which version it's running), but it _might_ come with a separate Python runtime that's separate from the version you were originally using, or it may have replaced the old version with a new installation and cleaned house.

According to [this post on StackExchange](https://stackoverflow.com/questions/53312590/how-can-i-check-all-the-installed-python-versions-on-windows), one way to check how many Python installs you have is to open a command prompt and type `py -0p` - if you do end up having multiple Python runtimes, it's also possible that the bleak you're installing might be going to one of the other runtimes instead of the version you're trying to run NeewerLite-Python in.

**Comment by markvrepo** [comment]
You nailed it.  Thanks.  I had a second python under a Visual Studio directory.

**Comment by taburineagle** [comment]
Ah, excellent - glad you were able to get that sorted!
