### ISSUE TITLE
Use regular HTTP parameter characters (? and &) instead of custom pipe characters

### ISSUE THREAD

**Issue by DanielBaulig** [taburineagle/NeewerLite-Python#9]
When trying to use the pipe character, various HTTP implementations (including Chrome browser) automatically replace the | character with %7 which is the URL encoded version of this character. NeewerLite-Python does not handle this character correctly.

I would like to recommend to use the regular HTTP query parameter syntax  instead of the pipe character. Regular HTTP query parameters look like follows:

http://server:port/path?parameter1=value1

http://server:port/path?parameter1=value1&parameter2=value2

http://server:port/path?parameter1=value1&parameter2=value2&parameter3=value3

I wouldn't be surprised if pythons built-in HTTP library can already correctly parse and handle those without the need to reinvent the wheel and use something like pipe characters.

**Comment by taburineagle** [comment]
Ah, yeah, like a PHP request format - I wasn't aware of the URL encoding change, the ampersand character would definitely be better in that instance.  I could theoretically do `NeewerLite-Python?item1=value1&...`, but I still prefer the `/NeewerLite-Python/` path structure for the time being.  Honestly, the easiest method to fix this would just be to change the separator to an ampersand instead of a pipe character, so I'll do that now.  The format will most likely stay similar, just with ampersands -

`http://server:port/NeewerLite-Python/light=11:22:33:44:55:66&mode=HSI&bri=50...`

**Comment by taburineagle** [comment]
Try the latest commit out when you have a chance - in Chrome, the URL is now parsed properly in my testing.

**Comment by DanielBaulig** [comment]
That’s awesome! Thank you.

Btw, for a technically correct and valid URL, you want to start the query string parameter part with a question mark ? and concatinate additional parameters with an ampersand. You can keep the path structure using one of two approaches:

Make the „light“ part a query parameter but retain the trailing slash on the NeewerLite-Python part, which is valid:
http://localhost:8080/NeewerLite-Python/?light=1;2&off

Make the /light part part of the path, and introduce an explicit query parameter to identify the lights, e.g.

http://localhost:8080/NeewerLite-Python/light?id=1;2&off
or
http://localhost:8080/NeewerLite-Python/light?address=1;2&off

Just making proposals. In the end you’ll probably be saving yourself and users headache by retaining RFC 2396 valid URLs.

**Comment by taburineagle** [comment]
Got you, that makes sense - I might just add a keyword similar to the light one in your example, but a "do-all" kind of action, like just the word `action` or `doAction`, etc. - the parser for `light=` is the same parser that the CLI uses to refer to the light, and both the HTTP server and CLI use the same argument parser, so I don't want to add too many changes to the base (post-/) structure of the URL, but something like that would conform more to traditional URL specs.  That one's another one I'm going to have to look into over the weekend :)  I may end up doing a similar thing I did to my latest commit, because the actual parsing without that ? does work fine (once the separator is separated correctly, it gets handed to the argument parser and parsed correctly into the correct arguments) - I may just remove that section from the URL before sending it off to the parser.  More to look into, hopefully soon.

**Comment by taburineagle** [comment]
OK!  I have added the correct URL parameter formatting across the board now - so a URL for the HTTP server looks like this:

`http://127.0.0.1:8000/NeewerLite-Python/doAction?light=1&mode=HSI&hue=240&bri=50`

**Comment by taburineagle** [comment]
Hello @DanielBaulig!  Closing this one also as it's been 7 days, and I have changed the HTTP URL syntax to match the request - if you have any issues related to this ticket, please feel free to re-open it!

**Comment by DanielBaulig** [comment]
Awesome, thank you for doing this!

**Comment by taburineagle** [comment]
You're welcome!
